version: 0.0
os: linux
files:
  - source: ./
    destination: /var/www/html
hooks:
  BeforeInstall:
    - location: scripts/status.sh
      timeout: 300
      runas: ubuntu 
  AfterInstall:
    - location: scripts/restart.sh 
      timeout: 300
      runas: ubuntu
